/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "uip.h"
#include <stdint.h>
#include "rcc.h"
#include "gpio.h"
#include "uartF051.h"
#include "spiF051.h"
#include "main.h"
//#include "ethernetif.h"
#include "STM32F0Time.h"
#include "timer.h"
#include "uip_arp.h"

volatile uint32_t timerTickCount = 0;

ENC28J60_ConfigTypeDef encdevice = {
		.full_duplex = true,
		.auto_negotiation = false,
};
struct uip_eth_addr my_mac = {{0x00, 0x04, 0xA3, 0x11, 0x22, 0x33}};

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

void Delay_ms(uint32_t ms) {
    volatile uint32_t i, j;
    for (i = 0; i < ms; i++) {
        for (j = 0; j < 8000; j++) {
            //__NOP();
        }
    }
}

// Example configuration for 48MHz system clock using PLL from HSE
void SystemClock_Config_48MHz(void) {
    RCC_Config rcc_config;

    /* Configure RCC for 48MHz using PLL with HSI */
    rcc_config.system_clock_source = CLOCK_SOURCE_PLL;
    rcc_config.target_frequency = SYSTEM_CLOCK_48MHZ;
    rcc_config.hse_enabled = false;
    rcc_config.pll_enabled = true;
    rcc_config.pll_source = PLL_SOURCE_HSI_DIV2;
    rcc_config.pll_multiplier = 12;  /* HSI (8MHz/2) * 12 = 48MHz */
    rcc_config.ahb_prescaler = AHB_PRESCALER_1;
    rcc_config.apb_prescaler = APB_PRESCALER_1;
    rcc_config.hsi48_enabled = false;
    rcc_config.css_enabled = false;

    /* Initialize RCC */
    RCC_Init(&rcc_config);
}

/*============================================================================
 * Example 1: LED Blink (GPIO Output)
 *============================================================================*/
void Example_LED_Blink(void) {
    GPIO_InitTypeDef GPIO_InitStruct = {0};

    /* Enable GPIOC clock for LED on PC8 */
    GPIO_EnableClock(GPIOC);

    /* Configure PC8 as output */
    GPIO_InitStruct.Pin = GPIO_PIN_8;
    GPIO_InitStruct.Mode = GPIO_MODE_OUTPUT;
    GPIO_InitStruct.Ot = GPIO_OTYPE_PP;
    GPIO_InitStruct.Speed = GPIO_SPEED_LOW;
    GPIO_InitStruct.Pull = GPIO_PULL_NO;
    GPIO_Init(GPIOC, &GPIO_InitStruct);
    GPIO_InitStruct.Pin = GPIO_PIN_9;
    GPIO_Init(GPIOC, &GPIO_InitStruct);

}


clock_time_t clock_time(void)
{
  return timerTickCount;
}

static void Timer2_Callback(void) {
    timerTickCount++;
    if(timerTickCount % 100 == 0)
    {
        GPIO_TogglePin(GPIOC, GPIO_PIN_8);
    }
}

void initializaTimer(void)
{
	uint32_t t2clk = STM32F0Timer_GetTimerClockHz(TIMER2);
	// TIMER2: 1 second = 1,000,000 us (1 Hz)
	if (!STM32F0Timer_ConfigurePeriodUs(TIMER2, t2clk, 10000)) {
		while (1);
	}

	STM32F0Timer_SetUpdateCallback(TIMER2, Timer2_Callback);

    // Enable update interrupts (NVIC priority in helper)
    STM32F0Timer_EnableUpdateInterrupt(TIMER2, true);

    // Start timers
    STM32F0Timer_Start(TIMER2);
}

uint16_t network_device_read(void)
{
	volatile uint16_t len = 0;
	len = getPackatLen();
	if(len > 0)
		{
			ENC28J60_ReceivePacket(uip_buf, len);
			return len;
		}
	else
	{
		return 0;
	}
}

void network_device_send()
{
	ENC28J60_SendPacket(uip_buf, uip_len);
}

void example_app_call(void) {
    if (uip_connected()) {
        // A new TCP connection has been established
    }

    if (uip_newdata()) {
        // Data received! Read buffer from uip_appdata
        // Example: Echoing received data back
        uip_send(uip_appdata, uip_datalen());
    }

    if (uip_acked()) {
        // Previously sent data was acknowledged by the remote host
    }

    if (uip_closed() || uip_aborted() || uip_timedout()) {
        // Connection closed or lost
    }
}

void uip_log(char *msg)
{
    UART_SendStringIT(USART1, msg);
}

#define BUF ((struct uip_eth_hdr *)&uip_buf[0])

int main(void)
{
	int i;
	uip_ipaddr_t ipaddr;
	struct timer periodic_timer, arp_timer;

	SystemClock_Config_48MHz();
	Delay_ms(30);
	Example_LED_Blink();
	/* Initialize UART for interrupt mode at 115200 baud */
	uart1_initialize();
	initializaTimer();
	//-----------------------------------------------------//
	encdevice.mac_addr[0] = my_mac.addr[0];
	encdevice.mac_addr[1] = my_mac.addr[1];
	encdevice.mac_addr[2] = my_mac.addr[2];
	encdevice.mac_addr[3] = my_mac.addr[3];
	encdevice.mac_addr[4] = my_mac.addr[4];
	encdevice.mac_addr[5] = my_mac.addr[5];

	ENC28J60_Init(&encdevice);
	uip_setethaddr(my_mac);
	//--------------------------------------------------//
	UART_SendStringIT(USART1, "System Starting...\n");

	//------------- uip setup -------------------//
	timer_set(&periodic_timer, CLOCK_SECOND / 2);
	timer_set(&arp_timer, CLOCK_SECOND * 10);

	uip_init();

	uip_ipaddr(ipaddr, 192, 168, 29, 111);
	uip_sethostaddr(ipaddr);

	// 3. Start Listening on TCP Port (e.g., Port 80 or 8080)
	uip_listen(HTONS(8080));
	//-------------------------------------------//

	while(1) {
	    uip_len = network_device_read();
	    if(uip_len > 0) {
	      if(BUF->type == htons(UIP_ETHTYPE_IP)) {
		uip_arp_ipin();
		uip_input();
		/* If the above function invocation resulted in data that
		   should be sent out on the network, the global variable
		   uip_len is set to a value > 0. */
		if(uip_len > 0) {
		  uip_arp_out();
		  network_device_send();
		}
	      } else if(BUF->type == htons(UIP_ETHTYPE_ARP)) {
		uip_arp_arpin();
		/* If the above function invocation resulted in data that
		   should be sent out on the network, the global variable
		   uip_len is set to a value > 0. */
		if(uip_len > 0) {
		  network_device_send();
		}
	      }

	    } else if(timer_expired(&periodic_timer)) {
	      timer_reset(&periodic_timer);
	      for(i = 0; i < UIP_CONNS; i++) {
		uip_periodic(i);
		/* If the above function invocation resulted in data that
		   should be sent out on the network, the global variable
		   uip_len is set to a value > 0. */
		if(uip_len > 0) {
		  uip_arp_out();
		  network_device_send();
		}
	      }

	#if UIP_UDP
	      for(i = 0; i < UIP_UDP_CONNS; i++) {
		uip_udp_periodic(i);
		/* If the above function invocation resulted in data that
		   should be sent out on the network, the global variable
		   uip_len is set to a value > 0. */
		if(uip_len > 0) {
		  uip_arp_out();
		  network_device_send();
		}
	      }
	#endif /* UIP_UDP */

	      /* Call the ARP timer function every 10 seconds. */
	      if(timer_expired(&arp_timer)) {
		timer_reset(&arp_timer);
		uip_arp_timer();
	      }
	    }
	    Delay_ms(50);
	  }

    /* Loop forever */
    /* Main loop - toggle LED */
    while (1) {

    	GPIO_TogglePin(GPIOC, GPIO_PIN_9);
        Delay_ms(500);
        //UART_SendStringIT(USART1, "Hello STM32\n");
    }
}
