/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "RCCH743ZI.h"
#include "GPIOH743ZI.h"

#define HSE_FREQUENCY_8MHZ       8000000UL
#define TARGET_SYSCLK_4MHZ        4000000UL
#define TARGET_SYSCLK_16MHZ       16000000UL
#define TARGET_SYSCLK_480MHZ      480000000UL
/* Board mapping used by all examples:
 *   LED    -> PB14
 *   Switch -> PG0   (assumed active-low; pressed = pin reads LOW)
 */
#define LED_PORT        GPIOB
#define LED_PIN         14

#define SW_PORT         GPIOG
#define SW_PIN          0

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

volatile uint32_t g_tick = 0;

void SysTick_Init(uint32_t reload) {
    SYSTICK_LOAD = reload;
    SYSTICK_VAL = 0;
    SYSTICK_CTRL = (1 << 2) | (1 << 1) | (1 << 0);
}

void SysTick_Handler(void) {
    g_tick++;
}

void Delay_Init(void) {
    SysTick_Init((RCC_GetSYSCLKFrequency() / 1000) - 1);
}

void Delay_ms(uint32_t ms) {
    uint32_t start = g_tick;
    while ((g_tick - start) < ms);
}

void RCC_PrintClockInfo(void) {
    volatile uint32_t sysclk = RCC_GetSYSCLKFrequency();
    volatile uint32_t hclk = RCC_GetHCLKFrequency();
    volatile uint32_t pclk1 = RCC_GetPCLK1Frequency();
    volatile uint32_t pclk2 = RCC_GetPCLK2Frequency();
    volatile SystemClockSource src = RCC_GetSystemClockSource();

    (void)sysclk;
    (void)hclk;
    (void)pclk1;
    (void)pclk2;
    (void)src;
}

void Example_1A_HSI_4MHz(void) {
    PLL_Config pll_config;
    pll_config.pll_source = PLL_SOURCE_HSI;
    pll_config.pll_m = 16;
    pll_config.pll_n = 16;
    pll_config.pll_p = 2;
    pll_config.pll_q = 2;
    pll_config.pll_r = 2;
    RCC_SystemClockConfig_PLL(&pll_config, TARGET_SYSCLK_4MHZ);
}


/* ---------------------------------------------------------------------
 *  Shared pin setup helpers, used by all examples to avoid duplicating
 *  the configuration descriptors (which could otherwise drift apart).
 * ------------------------------------------------------------------- */
void LED_Init(void) {
    GPIO_PinConfig led;
    led.pin       = LED_PIN;
    led.mode      = GPIO_MODE_OUTPUT;
    led.otype     = GPIO_OTYPE_PUSHPULL;
    led.speed     = GPIO_SPEED_LOW;
    led.pull      = GPIO_PULL_NONE;
    led.alternate = 0;
    GPIO_Init(LED_PORT, &led);
}

int main(void) {
    Delay_Init();

    Example_1A_HSI_4MHz();
    Delay_ms(100);
    RCC_PrintClockInfo();
//
//    Example_2A_HSE_16MHz();
//    Delay_ms(100);
//    RCC_PrintClockInfo();
//
//    Example_3B_PLL_480MHz();
//    Delay_ms(100);
//    RCC_PrintClockInfo();
    LED_Init();


    while (1) {
    	GPIO_TogglePin(LED_PORT, LED_PIN);
        Delay_ms(1000);
    }

    return 0;
}
