/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "RCCH743ZI.h"
#include "GPIOH743ZI.h"
#include "h7pwr.h"

//------------ Power control -------------//

//---------------------------------------//

#define HSE_FREQUENCY_8MHZ       8000000UL
#define TARGET_SYSCLK_4MHZ        4000000UL
#define TARGET_SYSCLK_16MHZ       16000000UL
#define TARGET_SYSCLK_480MHZ      480000000UL
/* Board mapping used by all examples:
 *   LED    -> PB14
 *   Switch -> PG0   (assumed active-low; pressed = pin reads LOW)
 */
#define LED1_PORT        GPIOB
#define LED1_PIN         14
#define LED2_PORT        GPIOE
#define LED2_PIN         1

#define SW_PORT         GPIOG
#define SW_PIN          0

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

void SystemClock_16MHz_HSI(void)
{
    RCC_HSIEnable(1);
    while (!RCC_HSIRdy()) { /* wait */ }

    /* HSIDIV = /4  =>  hsi_ck = 16 MHz */
    RCC_HSIConfig(2);          /* 2 = divide by 4 */

    RCC_SetFlashLatency(0);

    RCC_SetD1CPRE(AHB_PRESCALER_DIV1);
    RCC_SetAHBPrescaler(AHB_PRESCALER_DIV1);
    RCC_SetD1PPRE(APB_PRESCALER_DIV1);
    RCC_SetD2PPRE1(APB_PRESCALER_DIV1);
    RCC_SetD2PPRE2(APB_PRESCALER_DIV1);
    RCC_SetD3PPRE(APB_PRESCALER_DIV1);

    RCC_SetSysClockSrc(RCC_SYSCLK_HSI);
}

/* ---------------------------------------------------------------------
 *  Shared pin setup helpers, used by all examples to avoid duplicating
 *  the configuration descriptors (which could otherwise drift apart).
 * ------------------------------------------------------------------- */
void LED_Init(void) {
    GPIO_PinConfig led;
    led.pin       = LED1_PIN;
    led.mode      = GPIO_MODE_OUTPUT;
    led.otype     = GPIO_OTYPE_PUSHPULL;
    led.speed     = GPIO_SPEED_LOW;
    led.pull      = GPIO_PULL_NONE;
    led.alternate = 0;
    GPIO_Init(LED1_PORT, &led);

    led.pin       = LED2_PIN;
    GPIO_Init(LED2_PORT, &led);
}

int main(void) {
	RCC_PeriphEnable(RCC_APB4_SYSCFG);
	PWR_Init();

	RCC_PeriphEnable(RCC_AHB4_GPIOB);
	RCC_PeriphEnable(RCC_AHB4_GPIOE);


	SystemClock_16MHz_HSI();

    LED_Init();


    while (1) {
    	GPIO_TogglePin(LED1_PORT, LED1_PIN);
    	GPIO_TogglePin(LED2_PORT, LED2_PIN);
    	for(int i = 0; i < 500; i++)
    		for(int j = 0; j < 500; j++);
    }

    return 0;
}
