/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#define RCC_BASE			0x40021000UL
#define RCC_CR_OFFSET		0x00UL
#define RCC_CFGR_OFFSET		0x04UL


#define RCC_CR				(RCC_BASE+RCC_CR_OFFSET)
#define RCC_CFGR			(RCC_BASE+RCC_CFGR_OFFSET)


typedef struct
{
	uint32_t HSION     : 1;  // LSB + 0
	uint32_t HSIRDY    : 1;  // LSB + 1
	uint32_t HSITRIM   : 5;  // LSB + 2 to LSB + 6
	uint32_t HSICAL    : 8;  // LSB + 7 to LSB + 14
	uint32_t           : 1;  // LSB + 15 (unused)
	uint32_t HSEON     : 1;  // LSB + 16
	uint32_t HSERDY    : 1;  // LSB + 17
	uint32_t HSEBYP    : 1;  // LSB + 18
	uint32_t CSSON     : 1;  // LSB + 19
	uint32_t           : 4;  // LSB + 20 to LSB + 23
	uint32_t PLLON     : 1;  // LSB + 24
	uint32_t PLLRDY    : 1;  // LSB + 25
	uint32_t           : 6;  // LSB + 26 to LSB + 31
} RCC_CR_t;

typedef struct
{
    uint32_t SW          : 2;
    uint32_t SWS         : 2;
    uint32_t HPRE        : 4;
    uint32_t PPRE        : 3;
    uint32_t             : 3;
    uint32_t ADCPRE      : 1;
    uint32_t PLL_SRC     : 2;
    uint32_t PLL_XTPRE   : 1;
    uint32_t PLLMUL      : 4;
    uint32_t             : 2;
    uint32_t MCO         : 4;
    uint32_t MCOPRE      : 3;
    uint32_t PLL_NODIV   : 1;
} RCC_CFGR_t;

void SysClock_Config(void)
{
	RCC_CR_t *RCC_Cr = (RCC_CR_t *)RCC_CR;
	RCC_CFGR_t *RCC_Cfgr = (RCC_CFGR_t *)RCC_CFGR;

	//SystemClock_Init();
	RCC_Cr->HSION = 1;
	while(!RCC_Cr->HSIRDY);
	RCC_Cr->PLLON = 0;			// Disabled the PLL

	RCC_Cfgr->MCO = 5;			// Internal RC 8 MHz (HSI) oscillator clock selected
	RCC_Cfgr->PLLMUL = 6;		// Multiply by 8

	RCC_Cr->PLLON = 1;
	while(!RCC_Cr->PLLRDY);
}

int main(void)
{
	SysClock_Config();
    /* Loop forever */
	for(;;);
}
