/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "rcc.h"
#include "gpio.h"
#include "spiF051.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

volatile uint8_t Interrupt_Count = 0;

enum{
	DATA_MODE_8Bit,
	DATA_MODE_8Bit_CRC,
};

uint8_t SpiDataMode = DATA_MODE_8Bit;

uint8_t transfer_complete_int = false;
uint8_t Txnum = 0;

SPI_HandleTypeDef hspi1;
uint8_t tx_data[100] = {0x55};
uint8_t rx_data[10];

uint8_t *SpiTxPtr = 0;
uint8_t sendDataaCnt = 0;

uint8_t *SpiRxPtr = 0;
uint8_t receiveDataaCnt = 0;

volatile uint8_t TxXfrerCnt = 0;
volatile uint8_t RxXfrerCnt = 0;

uint16_t transfer_error_int = 0;



void Delay_ms(uint32_t ms) {
    uint32_t i, j;
    for (i = 0; i < ms; i++) {
        for (j = 0; j < 8000; j++) {
            asm("nop");
        }
    }
}

void SystemClock_Config_8MHz(void) {
    RCC_Config config = {
        .system_clock_source = CLOCK_SOURCE_HSI,
        .target_frequency = SYSTEM_CLOCK_8MHZ,
        .hse_enabled = false,
        .pll_enabled = false,
        .pll_source = PLL_SOURCE_HSI_DIV2,
        .pll_multiplier = 2,
        .ahb_prescaler = AHB_PRESCALER_1,
        .apb_prescaler = APB_PRESCALER_1,
        .hsi48_enabled = false,
        .css_enabled = false
    };

    RCC_Init(&config);
}

void Example_LED_Blink(void) {
    GPIO_InitTypeDef GPIO_InitStruct = {0};

    /* Enable GPIOC clock for LED on PC8 */
    GPIO_EnableClock(GPIOC);

    /* Configure PC8 as output */
    GPIO_InitStruct.Pin = GPIO_PIN_9;
    GPIO_InitStruct.Mode = GPIO_MODE_OUTPUT;
    GPIO_InitStruct.Ot = GPIO_OTYPE_PP;
    GPIO_InitStruct.Speed = GPIO_SPEED_MEDIUM;
    GPIO_InitStruct.Pull = GPIO_PULL_NO;
    GPIO_InitStruct.AF = GPIO_AF0;
    GPIO_Init(GPIOC, &GPIO_InitStruct);
}

void Example_Pin_Init(void) {
    GPIO_InitTypeDef GPIO_InitStruct = {0};

    /* Enable GPIOA for button */
    GPIO_EnableClock(GPIOA);
    GPIO_InitStruct.Pin = GPIO_PIN_0;
    GPIO_InitStruct.Mode = GPIO_MODE_INPUT;
    GPIO_InitStruct.Ot = GPIO_OTYPE_PP;
    GPIO_InitStruct.Speed = GPIO_SPEED_LOW;
    GPIO_InitStruct.Pull = GPIO_PULL_NO;
    GPIO_Init(GPIOA, &GPIO_InitStruct);

    /* Configure EXTI Line 0 for PA0 */
    SYSCFG_CR &= ~(0x0F);  /* Clear SYSCFG_EXTI0 bits */
    SYSCFG_CR |= (0x00);   /* Select GPIOA for EXTI0 */
    EXTI_IMR |= EXTI_LINE_0;       /* Enable EXTI Line 0 */
    EXTI_RTSR |= EXTI_LINE_0;     /* Enable rising edge trigger */
    EXTI_FTSR &= ~EXTI_LINE_0;    /* Disable falling edge trigger */
    EXTI_PR = EXTI_LINE_0;        /* Clear pending bit */

    /* Configure NVIC for EXTI0_1 IRQ */
    NVIC_EnableIRQ(EXTI0_1_IRQn);
    NVIC_SetPriority(EXTI0_1_IRQn, 3);  /* Lowest priority */
}


void SPI1_Init_Mode0_8bit(void)
{
    hspi1.Instance = SPI1;
    hspi1.Init.mode = SPI_MODE_MASTER;
    hspi1.Init.clock_polarity = SPI_CLOCK_POLARITY_LOW;   // CPOL = 0
    hspi1.Init.clock_phase = SPI_CLOCK_PHASE_1ST_EDGE;   // CPHA = 0
    hspi1.Init.frame_format = SPI_FRAME_FORMAT_MSB_FIRST;
    hspi1.Init.data_size = SPI_DATA_SIZE_8BIT;
    hspi1.Init.baud_rate = SPI_BAUD_RATE_DIV_16;
    hspi1.Init.comm_mode = SPI_COMM_MODE_FULL_DUPLEX;
    hspi1.Init.nss_mode = SPI_NSS_SOFTWARE; //
    hspi1.Init.protocol = SPI_FRAME_FORMAT_MOTOROLA;
    hspi1.Init.rx_fifo_threshold = SPI_FIFO_THRESHOLD_1_2;
    hspi1.Init.crc_enabled = false;
    hspi1.Init.crc_polynomial = 7;
    hspi1.Init.nss_pulse_enabled = false;

    // CRITICAL FIX: Set NSS pin HIGH via GPIO BEFORE initializing SPI
    // This prevents MODF (Mode Fault) when using software slave management
    GPIO_SetPin(GPIOA, GPIO_PIN_4);  // NSS HIGH via GPIO

    SPI_Init(&hspi1);
    // Enable NVIC interrupt for SPI1 (IRQ 25)
    NVIC_EnableIRQ(SPI1_IRQn);
    NVIC_SetPriority(SPI1_IRQn, 0);

    // Enable interrupts
    SPI_Enable(&hspi1);
}

void SPI1_Init_Mode0_CRC(void)
{
    hspi1.Instance = SPI1;
    hspi1.Init.mode = SPI_MODE_MASTER;
    hspi1.Init.clock_polarity = SPI_CLOCK_POLARITY_LOW;   // CPOL = 0
    hspi1.Init.clock_phase = SPI_CLOCK_PHASE_1ST_EDGE;   // CPHA = 0
    hspi1.Init.frame_format = SPI_FRAME_FORMAT_MSB_FIRST;
    hspi1.Init.data_size = SPI_DATA_SIZE_8BIT;
    hspi1.Init.baud_rate = SPI_BAUD_RATE_DIV_16;
    hspi1.Init.comm_mode = SPI_COMM_MODE_FULL_DUPLEX;
    hspi1.Init.nss_mode = SPI_NSS_SOFTWARE; //
    hspi1.Init.protocol = SPI_FRAME_FORMAT_MOTOROLA;
    hspi1.Init.rx_fifo_threshold = SPI_FIFO_THRESHOLD_1_2;
    hspi1.Init.crc_enabled = true;
    hspi1.Init.crc_polynomial = 7;
    hspi1.Init.nss_pulse_enabled = false;

    // CRITICAL FIX: Set NSS pin HIGH via GPIO BEFORE initializing SPI
    // This prevents MODF (Mode Fault) when using software slave management
    GPIO_SetPin(GPIOA, GPIO_PIN_4);  // NSS HIGH via GPIO

    SPI_Init(&hspi1);
    // Enable NVIC interrupt for SPI1 (IRQ 25)
    NVIC_EnableIRQ(SPI1_IRQn);
    NVIC_SetPriority(SPI1_IRQn, 0);

    // Enable interrupts
    SPI_Enable(&hspi1);


}

void SPI1_GPIO_Init(void)
{
    GPIO_InitTypeDef GPIO_InitStruct;

    // Enable GPIOA clock
    GPIO_EnableClock(GPIOA);

    // Configure NSS (PA4) as GPIO output - Manual slave select control
    // This pin will be controlled manually, not by SPI hardware
    GPIO_InitStruct.Pin = GPIO_PIN_4;
    GPIO_InitStruct.Mode = GPIO_MODE_OUTPUT;
    GPIO_InitStruct.Ot = GPIO_OTYPE_PP;
    GPIO_InitStruct.Speed = GPIO_SPEED_HIGH;
    GPIO_InitStruct.Pull = GPIO_PULL_UP;  // No pull-up/down for NSS
    GPIO_InitStruct.AF = GPIO_AF0;
    GPIO_Init(GPIOA, &GPIO_InitStruct);

    // Set NSS pin HIGH initially (inactive) - IMPORTANT for MODF prevention
    GPIO_SetPin(GPIOA, GPIO_PIN_4);

    // Configure SCK (PA5) - SPI1_SCK
    GPIO_InitStruct.Pin = GPIO_PIN_5;
    GPIO_InitStruct.Mode = GPIO_MODE_ALTERNATE;
    GPIO_InitStruct.Ot = GPIO_OTYPE_PP;
    GPIO_InitStruct.Speed = GPIO_SPEED_HIGH;
    GPIO_InitStruct.Pull = GPIO_PULL_NO;
    GPIO_InitStruct.AF = GPIO_AF0;  // SPI1 uses AF0 on PA5
    GPIO_Init(GPIOA, &GPIO_InitStruct);

    // Configure MISO (PA6) - SPI1_MISO
    // IMPORTANT: MISO needs pull-up for proper idle state in master mode
    GPIO_InitStruct.Pin = GPIO_PIN_6;
    GPIO_InitStruct.Mode = GPIO_MODE_ALTERNATE;
    GPIO_InitStruct.Ot = GPIO_OTYPE_PP;
    GPIO_InitStruct.Speed = GPIO_SPEED_HIGH;
    GPIO_InitStruct.Pull = GPIO_PULL_UP;  // Pull-up for MISO (prevents floating)
    GPIO_InitStruct.AF = GPIO_AF0;  // SPI1 uses AF0 on PA6
    GPIO_Init(GPIOA, &GPIO_InitStruct);

    // Configure MOSI (PA7) - SPI1_MOSI
    GPIO_InitStruct.Pin = GPIO_PIN_7;
    GPIO_InitStruct.Mode = GPIO_MODE_ALTERNATE;
    GPIO_InitStruct.Ot = GPIO_OTYPE_PP;
    GPIO_InitStruct.Speed = GPIO_SPEED_HIGH;
    GPIO_InitStruct.Pull = GPIO_PULL_NO;
    GPIO_InitStruct.AF = GPIO_AF0;  // SPI1 uses AF0 on PA7
    GPIO_Init(GPIOA, &GPIO_InitStruct);
}

void sendDataIT_SPI(uint8_t *dataptr, uint16_t size)
{
	SpiDataMode = DATA_MODE_8Bit;
	GPIO_ResetPin(GPIOA, GPIO_PIN_4);
	SPI_SendData8(&hspi1, tx_data[0]);
	TxXfrerCnt = 1;
	SpiTxPtr = dataptr;
	sendDataaCnt = size;
	transfer_complete_int = false;
	SPI_EnableInterrupt(&hspi1, SPI_IT_TXE | SPI_IT_RXNE | SPI_IT_ERR);

}

void receiveDataIT_SPI(uint8_t *dataptr, uint8_t size)
{
	SpiDataMode = DATA_MODE_8Bit;
	GPIO_ResetPin(GPIOA, GPIO_PIN_4);
	//SPI_SendData8(&hspi1, 0);

	SpiRxPtr = dataptr;
	receiveDataaCnt = size;

	RxXfrerCnt = 0;
	transfer_complete_int = false;
	SPI_EnableInterrupt(&hspi1, SPI_IT_TXE | SPI_IT_RXNE | SPI_IT_ERR);

	while (hspi1.Instance->SR & SPI_SR_BSY);

}

void sendDataIT_SPI_CRC(uint8_t *dataptr, uint8_t size)
{
	SpiDataMode = DATA_MODE_8Bit_CRC;
	SPI_ResetCRC(&hspi1);
	GPIO_ResetPin(GPIOA, GPIO_PIN_4);
	//SPI_SendData8(&hspi1, tx_data[0]);
	SpiTxPtr = dataptr;
	sendDataaCnt = size;
	TxXfrerCnt = 1;
	transfer_complete_int = false;
	SPI_EnableInterrupt(&hspi1, SPI_IT_TXE | SPI_IT_RXNE | SPI_IT_ERR);

}

int main_Master_Rx_8bit(void)
{
	SPI1_GPIO_Init();
	Delay_ms(100);
	SPI1_Init_Mode0_8bit();
	receiveDataIT_SPI(rx_data, sizeof(rx_data));

	Txnum = 0;
	while(1)
	{
		if(transfer_complete_int == true)
		{
			Delay_ms(300);
			if(Txnum < 100)
			{
				Txnum++;
				receiveDataIT_SPI(rx_data, sizeof(rx_data));
			}
		}
	}
}

int main_Master_Tx_8bit(void) {
    // Configure system clock
	SystemClock_Config_8MHz();
	Example_LED_Blink();
	//Example_Pin_Init();

	SPI1_GPIO_Init();
	//SPI_EnableClock(SPI_INSTANCE_1);
	Delay_ms(100);
	SPI1_Init_Mode0_8bit();

	sendDataIT_SPI(tx_data, sizeof(tx_data));

	while(1)
	{
		//GPIO_SetPin(GPIOC, GPIO_PIN_9);

	    if(transfer_complete_int == true)
	    {
	    	Delay_ms(500);
	    	if(Txnum < 1)
	    	{
	    		Txnum++;
	    		sendDataIT_SPI(tx_data, sizeof(tx_data));
	    	}
		}
	}
    return 0;
}


int main_Master_Tx_8bit_With_CRC(void) {
    // Configure system clock
	SystemClock_Config_8MHz();
	Example_LED_Blink();
	//Example_Pin_Init();

	SPI1_GPIO_Init();
	//SPI_EnableClock(SPI_INSTANCE_1);
	Delay_ms(100);
	SPI1_Init_Mode0_CRC();

//	SpiTxPtr = tx_data;
//	uint32_t val1 = sizeof(SpiTxPtr);
//	val1 = sizeof(tx_data);

	sendDataIT_SPI_CRC(tx_data, sizeof(tx_data));

	while(1)
	{
		//GPIO_SetPin(GPIOC, GPIO_PIN_9);

	    if(transfer_complete_int == true)
	    {
	    	Delay_ms(500);
	    	if(Txnum < 1)
	    	{
	    		Txnum++;
	    		sendDataIT_SPI_CRC(tx_data, sizeof(tx_data));
	    	}
		}


	}
    return 0;
}



//------------------------------------ main code --------------------------------------//
int main(void) {
    // Configure system clock

	for(int i = 0; i < sizeof(tx_data); i++)
	{
		tx_data[i] = i;
	}

	main_Master_Tx_8bit();
    return 0;
}

void SPI1_IRQHandler(void)
{
	volatile uint32_t sr = hspi1.Instance->SR;

	// TXE interrupt - send next data
	if ((sr & SPI_SR_TXE) && ((sendDataaCnt > 0) || (receiveDataaCnt > 0)))
	{
		if ((TxXfrerCnt < sendDataaCnt) && (sendDataaCnt > 0))
		{
			SPI_SendData8(&hspi1, SpiTxPtr[TxXfrerCnt]);
			TxXfrerCnt++;
		}
		else
		{
			if((SpiDataMode == DATA_MODE_8Bit_CRC) && (TxXfrerCnt == sendDataaCnt) && (sendDataaCnt > 0))
			{
				SPI_TransmitCRC(&hspi1);
				TxXfrerCnt++;
			}

			if ((RxXfrerCnt < receiveDataaCnt) && (receiveDataaCnt > 0))
			{
				SPI_SendData8(&hspi1, 0);		// send dummy bytes
			}
		}
	}

	// RXNE interrupt - receive data
    if (sr & SPI_SR_RXNE) {

        if (RxXfrerCnt < receiveDataaCnt) {
        	SpiRxPtr[RxXfrerCnt] = SPI_ReceiveData8(&hspi1);
        	RxXfrerCnt++;
        }
    }

	// Error handling
	if (sr & ( SPI_SR_MODF | SPI_SR_CRCERR)) {
		transfer_error_int = sr;
	}

	if (TxXfrerCnt >= sendDataaCnt && RxXfrerCnt >= receiveDataaCnt)
	{
		// Wait for SPI to finish transmitting all data (BSY flag cleared)
		while (hspi1.Instance->SR & SPI_SR_BSY);

		transfer_complete_int = true;

		/* Configure NVIC for EXTI0_1 IRQ */
		GPIO_SetPin(GPIOA, GPIO_PIN_4);
		SPI_DisableInterrupt(&hspi1, SPI_IT_TXE | SPI_IT_RXNE | SPI_IT_ERR);
		receiveDataaCnt = sendDataaCnt = 0;
	}
}


void EXTI0_1_IRQHandler(void) {
    if (EXTI_GetFlag(EXTI_LINE_0)) {
        /* Clear interrupt flag */
        EXTI_ClearFlag(EXTI_LINE_0);

        /* Increment counter */
        Interrupt_Count++;
    }
}
