/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "rcc.h"
#include "gpio.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

volatile uint8_t Interrupt_Count = 0;

void Delay_ms(uint32_t ms) {
    uint32_t i, j;
    for (i = 0; i < ms; i++) {
        for (j = 0; j < 8000; j++) {
            asm("nop");
        }
    }
}

void SystemClock_Config_8MHz(void) {
    RCC_Config config = {
        .system_clock_source = CLOCK_SOURCE_HSI,
        .target_frequency = SYSTEM_CLOCK_8MHZ,
        .hse_enabled = false,
        .pll_enabled = false,
        .pll_source = PLL_SOURCE_HSI_DIV2,
        .pll_multiplier = 2,
        .ahb_prescaler = AHB_PRESCALER_1,
        .apb_prescaler = APB_PRESCALER_1,
        .hsi48_enabled = false,
        .css_enabled = false
    };

    RCC_Init(&config);
}

void Example_LED_Blink(void) {
    GPIO_InitTypeDef GPIO_InitStruct = {0};

    /* Enable GPIOC clock for LED on PC8 */
    GPIO_EnableClock(GPIOC);

    /* Configure PC8 as output */
    GPIO_InitStruct.Pin = GPIO_PIN_9;
    GPIO_InitStruct.Mode = GPIO_MODE_OUTPUT;
    GPIO_InitStruct.Ot = GPIO_OTYPE_PP;
    GPIO_InitStruct.Speed = GPIO_SPEED_MEDIUM;
    GPIO_InitStruct.Pull = GPIO_PULL_NO;
    GPIO_InitStruct.AF = GPIO_AF0;
    GPIO_Init(GPIOC, &GPIO_InitStruct);
}

void Example_Pin_Init(void) {
    GPIO_InitTypeDef GPIO_InitStruct = {0};

    /* Enable GPIOA for button */
    GPIO_EnableClock(GPIOA);
    GPIO_InitStruct.Pin = GPIO_PIN_0;
    GPIO_InitStruct.Mode = GPIO_MODE_INPUT;
    GPIO_InitStruct.Ot = GPIO_OTYPE_PP;
    GPIO_InitStruct.Speed = GPIO_SPEED_LOW;
    GPIO_InitStruct.Pull = GPIO_PULL_NO;
    GPIO_Init(GPIOA, &GPIO_InitStruct);

    /* Configure EXTI Line 0 for PA0 */
    SYSCFG_CR &= ~(0x0F);  /* Clear SYSCFG_EXTI0 bits */
    SYSCFG_CR |= (0x00);   /* Select GPIOA for EXTI0 */
    EXTI_IMR |= EXTI_LINE_0;       /* Enable EXTI Line 0 */
    EXTI_RTSR |= EXTI_LINE_0;     /* Enable rising edge trigger */
    EXTI_FTSR &= ~EXTI_LINE_0;    /* Disable falling edge trigger */
    EXTI_PR = EXTI_LINE_0;        /* Clear pending bit */

    /* Configure NVIC for EXTI0_1 IRQ */
    NVIC_EnableIRQ(EXTI0_1_IRQn);
    NVIC_SetPriority(EXTI0_1_IRQn, 3);  /* Lowest priority */
}


int main(void) {
    // Configure system clock
	SystemClock_Config_8MHz();
	Example_LED_Blink();
	Example_Pin_Init();

    // Enable peripheral clocks as needed

    // Get current system clock frequency
    uint32_t sysclk = RCC_GetSystemClockFrequency();

    /* Main loop */
    while (1) {
        /* LED reflects interrupt count (mod 2) */
        if (Interrupt_Count % 2) {
            GPIO_SetPin(GPIOC, GPIO_PIN_9);
        } else {
            GPIO_ResetPin(GPIOC, GPIO_PIN_9);
        }
    }
    return 0;
}


void EXTI0_1_IRQHandler(void) {
    if (EXTI_GetFlag(EXTI_LINE_0)) {
        /* Clear interrupt flag */
        EXTI_ClearFlag(EXTI_LINE_0);

        /* Increment counter */
        Interrupt_Count++;
    }
}
